### ISSUE TITLE
Handle resource binding leakage

### ISSUE THREAD

**Issue by JuanDiegoMontoya** [JuanDiegoMontoya/Fwog#52]
At the moment, a resource bound via any of the `Cmd::Bind*` functions will stay bound until another resource is bound to that slot. This means the bindings will escape rendering and compute scopes, which is against one of the core tenets of Fwog (preventing the possibility of state leakage).

Possible solutions:
1. In debug mode, zero all resource bindings when a rendering or compute scope begins. This should make it fairly obvious if leaked bindings are being relied on by the pass.
2. Using introspection, determine what resources need to be bound to a program before drawing or dispatching compute with it, then, in debug mode only, assert that a resource has been bound to each of the required bindings since the beginning of the rendering/compute scope. This would be more robust, but also more annoying to implement.

**Comment by deccer** [comment]
I think option one is the saner option out of the two. Either zero them out as you mentioned, or track the ones you set per pipeline, and zero those who are not required for a possible other pipeline

Option two sounds like more effort, the code you need to write to have introspection working complicates things and you are never sure if the driver may have a hand in removing things you are not using etc, that could be misleading for the user/consumer

**Comment by JuanDiegoMontoya** [comment]
Good points. I will implement the former option for now and revisit this if I come up with something better.
