### ISSUE TITLE
gltf viewer G-Buffers Preview Bug with Camera Movement

### ISSUE THREAD

**Issue by ClementineAccount** [JuanDiegoMontoya/Fwog#63]
Minor bug in 03_gltf_viewer.cpp where the 'sky' does not clear the buffer in the G-Buffer preview

https://user-images.githubusercontent.com/26779639/230547809-9f7c39de-6f48-4c1b-800a-f95df3e2e63d.mp4

**Comment by JuanDiegoMontoya** [comment]
This is actually not a bug, but rather a side effect of using `Fwog::AttachmentLoadOp::DONT_CARE` for the g-buffer images and displaying the resulting image. The unwritten parts have undefined contents (which is what you're seeing here), but the written parts are correctly written to and used for shading.
