### ISSUE TITLE
Suggestion: app_hello_square.cpp should show InputAssemblyState

### ISSUE THREAD

**Issue by ClementineAccount** [JuanDiegoMontoya/Fwog#64]
Currently, 01_hello_triangle is intended as a 'tutorial' project for a beginner and is documented as such. The knowledge of setting primitives coming from OpenGL, however, is not documented and requires the user to have had experience with Vulkan in order to infer the usage of an InputAssemblyState. 

The file of 01_hello_triangle could allow a soft introduction to the concept for someone coming from OpenGL through specifying the InputAssemblyState, even though the default is already TRIANGLE_LIST

![image](https://user-images.githubusercontent.com/26779639/230553969-dfc5307b-6ee6-4d54-a406-412a5b5c1080.png)

**Comment by JuanDiegoMontoya** [comment]
Good idea. I'll update the example to show this.
