### ISSUE TITLE
Following Warnings are Treated as Errors (Release Mode cannot compile)

### ISSUE THREAD

**Issue by ClementineAccount** [JuanDiegoMontoya/Fwog#69]
FWOG_ASSERT() in Release mode can trigger warning as error for the following:

![image](https://user-images.githubusercontent.com/26779639/232266479-2aac597f-e121-4f8f-9350-f8496343ef43.png)
![image](https://user-images.githubusercontent.com/26779639/232266459-25f8378c-d5df-4212-be0a-a1455290779e.png)

When using FetchContent() for my own fork that disables the Warning as Error (/WX) I was able to compile Fwog for my project in release mode. (https://github.com/ClementineAccount/Fwog/blob/main/CMakeLists.txt)

**Comment by JuanDiegoMontoya** [comment]
Hi @ClementineAccount. Try pulling and let me know if the fix worked.

**Comment by ClementineAccount** [comment]
> Hi @ClementineAccount. Try pulling and let me know if the fix worked.

Works perfectly. Thanks for the fix!
