### ISSUE TITLE
Dynamic graphics pipeline state

### ISSUE THREAD

**Issue by JuanDiegoMontoya** [JuanDiegoMontoya/Fwog#7]
Add the ability to set certain graphics pipeline state in a render pass without having to bind a new pipeline. This might seem antithetical to the design of Fwog, but sometimes it is useful to be able to cheaply change some minimal state between draws without having to bind an entire pipeline.

In drivers for modern desktop hardware, some state is practically free to change. The goal is to identify those states and add the common ones to Fwog.

Secondary goal: make a benchmark to test if dynamic state has the intended performance impact of zero.

**Comment by deccer** [comment]
Do we have a list of possible things, identifying as not intrusive, already?
something like viewport and scissor?

**Comment by JuanDiegoMontoya** [comment]
After doing some research, it is apparent that there is _no_ dynamic state which is truly free on _all_ hardware. However, scissor and viewport state is important enough and cheap enough on common hardware that they are included.

The main thing that needs to be watched for, at least on AMD hardware, is frequent changing of these pieces of state. This state is held in context registers and can cause a [stall](https://gpuopen.com/learn/understanding-gpu-context-rolls/) if the user is reckless. This seems to not be a problem on NV hardware.

There may be additional state which falls into a similar category as these. Until those are identified, I will be closing this issue.
