### ISSUE TITLE
Fwog fails to run on iGPUs (Examples detailed)

### ISSUE THREAD

**Issue by ClementineAccount** [JuanDiegoMontoya/Fwog#91]
# Summary 
I had recently changed laptops from a Razer Blade 2018 which had a dGPU of a GTX-1060M to a Lenovo 82Y0 which has an intergrated Intel(R) Iris(R) Xe Graphics. These hardware specifications should be more than capable at running OpenGL 4.6 as detailed in the following report generated by [GLview](http://www.realtech-vr.com/home/glview) (this also shows the available extensions): https://pastebin.com/iBrJpfqi

# Examples

## Fwog Template

I had first encountered problems through my [Fwog Template](https://github.com/ClementineAccount/Fwog-CMake-Glfw-OpenGL-Template) which detailed the following that is triggered upon a breakpoint in the following [Context.cpp](https://github.com/JuanDiegoMontoya/Fwog/blob/bb1d98bd3c8e05df240e1a23ce7d21ac81b06ac1/src/Context.cpp#L19) line:

![image](https://github.com/JuanDiegoMontoya/Fwog/assets/26779639/e0c3fa57-50a5-429b-bc97-a5b935ac934a)

`[2023-07-18 20:17:30.532] [error] GL CALLBACK: type = 33356, severity = error, message = Error has been generated. GL error GL_INVALID_VALUE in (null): (ID: 173538523) Generic error`

## 01_hello_triangle.cpp

In order to confirm that it was not on my end exclusively, I had also downloaded the [Release v0.2.0 of Fwog](https://github.com/JuanDiegoMontoya/Fwog/releases/tag/v0.2.0) in test the examples.

[01_hello_triange.cpp](https://github.com/JuanDiegoMontoya/Fwog/blob/bb1d98bd3c8e05df240e1a23ce7d21ac81b06ac1/example/01_hello_triangle.cpp) produces the following.

```
OpenGL Debug message (1281): Error has been generated. GL error GL_INVALID_VALUE in BindBufferRange: (ID: 2407551000) Generic error
Source: API
Type: Error
Severity: high
OpenGL Debug message (8): API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound.
Source: API
Type: Performance
Severity: low
```

## 02_deferred.cpp (Resolved)
This is the error I had while it was trying to compile the shader: [02_deferred.cpp](https://github.com/JuanDiegoMontoya/Fwog/blob/bb1d98bd3c8e05df240e1a23ce7d21ac81b06ac1/example/02_deferred.cpp)
```
WARNING: 0:3: '#extension' :  'GL_GOOGLE_include_directive' is not supported
ERROR: 0:141: '' : syntax error: no newline at end of directive #line
```

**Comment by JuanDiegoMontoya** [comment]
Hi @ClementineAccount. Try updating to the latest commit: 47396823e65ca0490d6a43635d67e389655ac8ff. It should fix the buffer (un)binding and shader compilation issues. The warning about the redundant framebuffer bind can be safely ignored.

As for the last issue, you should consult RenderDoc to see what is happening.

**Comment by ClementineAccount** [comment]
Found out last one caused by [GLFW_SCALE_TO_MONITOR](https://www.glfw.org/docs/3.3/window_guide.html) and has no relationship with Fwog. My laptop had the DPI Scaling over 100%. I will edit the original post to remove it.

As we had talked about on Discord, the `33356` error is still present even on this [commit](https://github.com/JuanDiegoMontoya/Fwog/commit/47396823e65ca0490d6a43635d67e389655ac8ff).

**Comment by JuanDiegoMontoya** [comment]
The issue was that Fwog was looping over `GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS` and clearing each binding instead of looping over `GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS`. It turns out that [certain Intel platforms](https://opengl.gpuinfo.org/displayreport.php?id=9639) have more available storage blocks than bindings, presumably for the purpose of memory aliasing. This led to Fwog to try clearing bindings that didn't exist, causing an error to be generated by the implementation.
